### PR TITLE
organization of commands in layout.py

### PR DESCRIPTION
**Pull request by CRAG666**
I think that an easier way to be able to add more commands in the future is through a collection, for these purposes and because of the structure it has, the function is favorable to use a dictionary, you could have a single dictionary but in some if it is compared in others it returns, in subsequent pr I will try to further separate that logic

### CODE REVIEW

**Review by jbuchermn — CHANGES_REQUESTED** [review]
Thank you! I think that's a good idea and keeps the code better structured.

Just one thing - I don't think it's necessary to separate `cmd_options` and `cmd_returned_options`. Returning `None` is the same as not returning anything. This makes it even cleaner.

**Comment by jbuchermn** [comment]
One other thing - I think we should write "inhibit-idle" and "finish-inhibit-idle" as lambdas as well.

**Comment by CRAG666** [comment]
Ok, so good that you tell me this, separate it more for reasons of not knowing the context of use, right now I apply this, I was tempted to do it but I felt that this change would be rejected, thank you for making me see that

**Comment by CRAG666** [comment]
@jbuchermn I already made the requested changes :)

**Comment by jbuchermn** [comment]
Did you check, if all the commands still work? Also I have some mypy complaints... can you fix these?

**Comment by CRAG666** [comment]
mypy? what do you mean by that?

**Comment by CRAG666** [comment]
@jbuchermn What is the specific mypy command that you use?

**Comment by CRAG666** [comment]
the commans its working

**Comment by jbuchermn** [comment]
There's a mypy.ini in the repo. I'll run some tests once mypy stops complaining :)

**Comment by CRAG666** [comment]
Introduje esos errores yo?

**Comment by CRAG666** [comment]
@jbuchermn  Did I introduce those errors?

**Comment by CRAG666** [comment]
I think the error was that it was returning reference to functions, it was not calling them, now I make that call

**Comment by CRAG666** [comment]
I am very sorry, sorry.
the correct line is this
``` python
cmd_options.get(cmd, lambda: "Unknown " + generic_msg)()
```

**Comment by CRAG666** [comment]
now it works fine :)

**Comment by jbuchermn** [comment]
Thanks for the update :) I think this should work. however you're still missing the type annotations, so there are still mypy errors. But I will try to fix that tomorrow; should not be hard.

**Comment by CRAG666** [comment]
Thank you, even though I still don't know why the errors if only str and None are returned

**Comment by jbuchermn** [comment]
See https://github.com/jbuchermn/newm/commit/2646a5946bc5d083b50468f01fd7834b85a56f35 for the adjustments I made before merging.

Thanks again for the PR!

**Pull request merged**
