### PR TITLE
Replace fuzzywuzzy with thefuzz

### PR DESCRIPTION
**Pull request by Pandademic**
⬆️

### CODE REVIEW

**Comment by jbuchermn** [comment]
Hi, you're right, the description has to be changed :) Can we remove `fuzzywuzzy` as a dependency, if `thefuzz` is added? Probably this requires some more changes.

**Comment by Pandademic** [comment]
@jbuchermn we can but we have to replace a lot in the main source files. Should I work on that as part of this PR?

**Comment by jbuchermn** [comment]
Yes, that would be great! I think you should mainly take a look at `newm_panel_basic/launcher.py`.

**Comment by Pandademic** [comment]
@jbuchermn I don't see where fuzzywuzzy is used at all in `newm_panel_basic/launcher.py` , I can only find the title. Are you sure this isn't a unused import?

**Comment by Pandademic** [comment]
actually for the whole project , here's what `ripgrep` pulls up for `fuzzywuzzy`:
```
setup.py
18:          'fuzzywuzzy'

requirements_mypy.txt
6:fuzzywuzzy

newm_panel_basic\launcher.py
12:from fuzzywuzzy import process

flake.nix
33:            fuzzywuzzy
``
The first 2 and last one being in deps and the 3 one being a import. No usage 🤷

**Comment by jbuchermn** [comment]
Take a closer look at the source code, the import is actually used:

```py
from fuzzywuzzy import process  # type: ignore
[...]
result = process.extract(search, list(entries.keys()), limit=10)
``` 

At first glance it looks like you can just replace

```̀py
from thefuzz import process
```

**Comment by Pandademic** [comment]
@jbuchermn sorry I didn't catch that when I looked through the file, I thought of that long after I commented , and could do nothing to fix it. Anyway, looks good after the latest commit(s). Is that really all that we need? Something feels a bit off....

**Comment by jbuchermn** [comment]
Looks great on first sight. I had to make some adjustment on nixOS files, but it appears to work.

**Comment by jbuchermn** [comment]
I incorporated my changes into https://github.com/jbuchermn/newm/pull/84 and will merge from there.

Thanks a lot :)

**Comment by Pandademic** [comment]
Yay!

**Pull request merged**
